window.SPIELER = [
  {
    name: "André",
    sprite: "assets/Trainer/blackbelt.png",
    currentTeam: [
      "Tapu Bulu",
      "Muk-Alola",
      "Camerupt-Mega",
      "Golisopod",
      "Drifblim",
      "Aurorus",
      "Magneton",
      "Gogoat",
      "Bronzor",
      "Maushold",
    ],
    currentTeamInfo: {
      "label": "low-power 2026-06-26",
      "format": "low-power",
      "date": "2026-06-26",
      "spentPoints": 73,
      "teraCaptain": "Aurorus",
      "teraType": "Ice",
      "zCaptain": "Gogoat",
      "zType": "Grass"
    },
    previousTeams: [],
    matchSiege: [],
    abendSiege: [],
    nudelsterne: 0,
  },
  {
    name: "Hans",
    sprite: "assets/Trainer/roughneck.png",
    currentTeam: [
      "Politoed",
      "Drednaw",
      "Breloom",
      "Dubwool",
      "Sandaconda",
      "Kilowattrel",
      "Bombirdier",
      "Centiskorch",
      "Mimikyu",
      "Dragonair",
    ],
    currentTeamInfo: {
      "label": "low-power 2026-06-26",
      "format": "low-power",
      "date": "2026-06-26",
      "spentPoints": 75,
      "teraCaptain": null,
      "teraType": null,
      "zCaptain": null,
      "zType": null
    },
    previousTeams: [],
    matchSiege: [],
    abendSiege: [],
    nudelsterne: 0,
  },
  {
    name: "Marc",
    sprite: "assets/Trainer/brycen.png",
    currentTeam: [
      "Bisharp",
      "Vikavolt",
      "Seismitoad",
      "Crobat",
      "Dachsbun",
      "Froslass",
      "Coalossal",
      "Medicham",
      "Zorua-Hisui",
      "Sableye",
    ],
    currentTeamInfo: {
      "label": "low-power 2026-06-26",
      "format": "low-power",
      "date": "2026-06-26",
      "spentPoints": 75,
      "teraCaptain": "Coalossal",
      "teraType": "Grass",
      "zCaptain": "Vikavolt",
      "zType": "Electric"
    },
    previousTeams: [],
    matchSiege: [],
    abendSiege: [],
    nudelsterne: 0,
  },
  {
    name: "Niklas",
    sprite: "assets/Trainer/n.png",
    currentTeam: [
      "Jellicent",
      "Togetic",
      "Braviary-Hisui",
      "Morpeko",
      "Aggron",
      "Magmortar",
      "Pinsir",
      "Sceptile-Mega",
      "Krookodile",
      "Toxicroak",
    ],
    currentTeamInfo: {
      "label": "low-power 2026-06-26",
      "format": "low-power",
      "date": "2026-06-26",
      "spentPoints": 75,
      "teraCaptain": null,
      "teraType": null,
      "zCaptain": "Pinsir",
      "zType": "Ground"
    },
    previousTeams: [],
    matchSiege: [],
    abendSiege: [],
    nudelsterne: 0,
  },
  {
    name: "Robin",
    sprite: "assets/Trainer/birdkeeper.png",
    currentTeam: [
      "Forretress",
      "Articuno-Galar",
      "Meganium",
      "Magmar",
      "Murkrow",
      "Wigglytuff",
      "Misdreavus",
      "Tauros-Paldea-Aqua",
      "Nidoqueen",
      "Dracozolt",
    ],
    currentTeamInfo: {
      "label": "low-power 2026-06-26",
      "format": "low-power",
      "date": "2026-06-26",
      "spentPoints": 75,
      "teraCaptain": "Magmar",
      "teraType": "Grass",
      "zCaptain": "Articuno-Galar",
      "zType": "Psychic"
    },
    previousTeams: [],
    matchSiege: [],
    abendSiege: [],
    nudelsterne: 0,
  },
  {
    name: "Stefan",
    sprite: "assets/Trainer/blue.png",
    currentTeam: [
      "Bronzong",
      "Nidoking",
      "Ampharos-Mega",
      "Slurpuff",
      "Sharpedo",
      "Rapidash",
      "Komala",
      "Illumise",
      "Virizion",
      "Cofagrigus",
    ],
    currentTeamInfo: {
      "label": "low-power 2026-06-26",
      "format": "low-power",
      "date": "2026-06-26",
      "spentPoints": 75,
      "teraCaptain": null,
      "teraType": null,
      "zCaptain": null,
      "zType": null
    },
    previousTeams: [],
    matchSiege: [],
    abendSiege: [],
    nudelsterne: 0,
  },
  {
    name: "Tobi",
    sprite: "assets/Trainer/pokemaniac.png",
    currentTeam: [
      "Arctozolt",
      "Pincurchin",
      "Eelektrik",
      "Beartic",
      "Espeon",
      "Gourgeist",
      "Pelipper",
      "Sirfetch’d",
      "Kingdra",
      "Shroodle",
    ],
    currentTeamInfo: {
      "label": "low-power 2026-06-26",
      "format": "low-power",
      "date": "2026-06-26",
      "spentPoints": 70,
      "teraCaptain": null,
      "teraType": null,
      "zCaptain": "Arctozolt",
      "zType": "Ice"
    },
    previousTeams: [],
    matchSiege: [],
    abendSiege: [],
    nudelsterne: 1,
  },
  {
    name: "Jannik",
    sprite: "assets/Trainer/red.png",
    currentTeam: [
      "Skeledirge",
      "Raichu-Alola",
      "Hitmonlee",
      "Thievul",
      "Thwackey",
      "Steelix",
      "Audino-Mega",
      "Blastoise",
      "Swalot",
      "Cryogonal",
      "Fearow",
    ],
    currentTeamInfo: {
      "label": "low-power 2026-06-26",
      "format": "low-power",
      "date": "2026-06-26",
      "spentPoints": 75,
      "teraCaptain": "Thievul",
      "teraType": "Ice",
      "zCaptain": null,
      "zType": null
    },
    previousTeams: [],
    matchSiege: [],
    abendSiege: [],
    nudelsterne: 0,
  },
];

/*
  Team examples:
  currentTeam: ['Charizard', 'Blastoise', 'Venusaur', 'Pikachu', 'Snorlax', 'Gengar', 'Dragonite', 'Lapras', 'Arcanine'],
  currentTeamInfo: { label: 'Low Power 2026-06-26', format: 'low-power', date: '2026-06-26' },
  previousTeams: [
    {
      label: 'Season 1',
      format: 'Normal',
      pokemon: ['Mew', 'Ditto', 'Rotom', 'Scizor', 'Milotic', 'Tyranitar', 'Flygon', 'Skarmory', 'Umbreon'],
    },
  ],

  Win examples:
  matchSiege: [
    { date: '2026-06-23', format: 'Normal', title: 'Finale gegen NAME' },
  ],
  abendSiege: [
    { date: '2026-06-23', format: 'Low Power', title: 'Draft Abend #1' },
  ],
*/
